name: Schedule Hello Script

on:
  schedule:
    - cron: '*/30 * * * *' # Triggers every 30 minutes
  workflow_dispatch: # Allows for manual trigger

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Setup Python 3.x environment
    - name: Install dependencies
      run: pip install -r requirements.txt # Assumes you have a requirements.txt, if not, this step can be skipped
    - name: Run hello.py
      run: python hello.py